### ISSUE TITLE
xbmc-imx vs. linux-wandboard-fsl version missmatch on a78823a015

### ISSUE THREAD

**Issue by jokogr** [CrawX/PKGBUILDs#3]
xbmc-imx depends on fsl-bsp-kernel=3.0.35_4.1.0 and fsl-bsp-kernel-headers=3.0.35_4.1.0, yet linux-wandboard-fsl provides fsl-bsp-kernel=4.1.0 and fsl-bsp-kernel-headers=4.1.0 (it gets directly ${_fslbspver}).

I would have made a pull request, but I don't know which is preferable, 3.0.35_4.1.0 or 4.1.0.

**Comment by CrawX** [comment]
I'll fix this for the moment using the "3.0.35_4.1.0"-alternative, but I think the whole depends-area needs some refactoring (sooner or later...).

Thanks for reporting!
